[package]
name = "thesis"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.9.1"
bevy_quinnet = "0.3"
mysql = "23.0.1"
rand = "0.8.5"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
simple-matrix = "0.1.2"
